### ISSUE TITLE
Seqs and Tools continually showing it needs to be updated in VCV Rack 2.1.1

### ISSUE THREAD

**Issue by pgatt** [AScustomWorks/Paid-Modules-Info#5]
Hi Alfredo,

Due to a separate issue that we've fixed, AS Seqs and Tools is now incorrectly showing that it needs to be updated.

Could you please remove lines of code that overwrite p->slug and p->version and then request an update?

We appreciate your time.

**Comment by AScustomWorks** [comment]
Hi!, at first I didn't know what you were talking about, but saw those lines... way old code leftover?(removed now)

I'll have to update the version too, right?

**Comment by pgatt** [comment]
That would be great! Thanks for fixing this so quickly Alfredo!

**Comment by AScustomWorks** [comment]
Already requested the update to Andrew, thanks!

**Comment by pgatt** [comment]
Thanks Alfredo, love your work!
